@WebApi_HostAddress = http://localhost:5212

GET {{WebApi_HostAddress}}/api/v1/forecasts
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/forecasts/1
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/v1/forecasts/f7afc8dc-c086-455f-8b1b-1f59faeac7b6
Accept: application/json

###
