name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: password1@
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433

    steps:
        - uses: actions/checkout@v4
        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ matrix.dotnet-version }}
        - name: Install dependencies
          run: dotnet restore src
        - name: Test with dotnet
          run: |
            echo '{"Database":{"ConnectionString":"Data Source=localhost;Initial Catalog=EFCore;user id=sa;password=password1@;TrustServerCertificate=True;"}}' > src/Relationships.Tests/appsettings.local.json
            cp src/Relationships.Tests/appsettings.local.json src/Transactions.Tests/appsettings.local.json
            dotnet test src --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
        - name: Upload dotnet test results
          uses: actions/upload-artifact@v4
          with:
            name: dotnet-results-${{ matrix.dotnet-version }}
            path: TestResults-${{ matrix.dotnet-version }}
          # Use always() to always run this step to publish test results when there are test failures
          if: ${{ always() }}
